### ISSUE TITLE
Query String getting broken

### ISSUE THREAD

**Issue by agerace** [inaka/Jayme#86]
On the `URLSessionBackend.swift` file, line 77. 
This method : 
`fileprivate func url(for path: Path) -> URL? {
        return self.baseURL?.appendingPathComponent(path)
    }`
Is encoding the path and changing ( for example ) the question marks ( ? ) for a %3F . This results in a bad URL error every time you include a question mark on the path.
This is the solution I found : 
`fileprivate func url(for path: Path) -> URL? {
        return URL(string: path, relativeTo: self.baseURL)
    }`
Since I'm too busy with a project right now, I hope you @volbap  can take a look at this and decide if this is a change worth to be applied or if we should look for another approach. I think it is pretty neat.

**Comment by volbap** [comment]
@agerace this is approved. Would you raise a Pull Request with this change?

**Comment by volbap** [comment]
Hey @agerace , thanks for your collaboration.

The code you propose breaks the "problematic URL" test.

I am not sure if what you are reporting here is correct. I modified the unit tests so that they assert the possibility of having query string characters (such as `?` and `&`) in the `path` parameter, and the tests pass successfully with the current code.

I've updated the tests in [this branch](https://github.com/inaka/Jayme/tree/pablo.QueryStringFix). Let me know if there are other specific steps to reproduce and if we should introduce any change in the code.

**Comment by volbap** [comment]
I stumbled upon the issue mentioned here when trying to call `future` on a `URLSessionBackend` with a path including `?` characters: I obtained the URL with the percent characters @agerace  mentioned.

I could manage to fix the test that was breaking: When a path has non-standard characters and the URL is expected not to be built, turns out that the `URL(string:, relativeTo:)` method is not returning `nil`, but it actually does return a URL with `"_"` as its `absoluteString`! So, I included a new condition where the `URL` should neither be `nil` nor has `"_"` as `absoluteString`.
